import type { GameBlueprint } from "../laboratory/types";
import type { Engine2DGenre, GenreProfile2D } from "./types";
const P:Record<Engine2DGenre,GenreProfile2D>={
monster_tamer:{genre:"monster_tamer",camera:"top_down",requiredSystems:["movement","collision","camera","dialogue","quest","encounter","battle","capture","party","inventory"],visualDefaults:{style:"original_pixel_art",camera:"top_down",paletteMood:"warm adventure",characterAnimation:true,tileBased:true},minimumScenes:2,requiredEntityKinds:["player","npc","creature","item"]},
farming:{genre:"farming",camera:"top_down",requiredSystems:["movement","collision","camera","dialogue","farming","economy","inventory"],visualDefaults:{style:"original_pixel_art",camera:"top_down",paletteMood:"cozy pastoral",characterAnimation:true,tileBased:true},minimumScenes:2,requiredEntityKinds:["player","npc","item"]},
adventure:{genre:"adventure",camera:"top_down",requiredSystems:["movement","collision","camera","dialogue","quest","inventory"],visualDefaults:{style:"original_pixel_art",camera:"top_down",paletteMood:"exploration",characterAnimation:true,tileBased:true},minimumScenes:2,requiredEntityKinds:["player","npc","item"]},
rpg:{genre:"rpg",camera:"top_down",requiredSystems:["movement","collision","camera","dialogue","quest","battle","inventory"],visualDefaults:{style:"original_pixel_art",camera:"top_down",paletteMood:"fantasy",characterAnimation:true,tileBased:true},minimumScenes:2,requiredEntityKinds:["player","npc","enemy","item"]},
platformer:{genre:"platformer",camera:"side_scroll",requiredSystems:["movement","collision","camera","platform"],visualDefaults:{style:"original_pixel_art",camera:"side_scroll",paletteMood:"arcade",characterAnimation:true,tileBased:false},minimumScenes:1,requiredEntityKinds:["player","obstacle","goal"]},
racing:{genre:"racing",camera:"follow",requiredSystems:["movement","collision","camera","racing"],visualDefaults:{style:"vector",camera:"follow",paletteMood:"high speed",characterAnimation:false,tileBased:false},minimumScenes:1,requiredEntityKinds:["player","obstacle","goal"]},
puzzle:{genre:"puzzle",camera:"top_down",requiredSystems:["movement","collision","camera","puzzle"],visualDefaults:{style:"vector",camera:"top_down",paletteMood:"clean logic",characterAnimation:false,tileBased:false},minimumScenes:1,requiredEntityKinds:["player","goal","obstacle"]},
shooter:{genre:"shooter",camera:"top_down",requiredSystems:["movement","collision","camera","shooting"],visualDefaults:{style:"original_pixel_art",camera:"top_down",paletteMood:"action",characterAnimation:true,tileBased:false},minimumScenes:1,requiredEntityKinds:["player","enemy","goal"]},
strategy:{genre:"strategy",camera:"top_down",requiredSystems:["camera","strategy","inventory"],visualDefaults:{style:"vector",camera:"top_down",paletteMood:"tactical",characterAnimation:false,tileBased:true},minimumScenes:1,requiredEntityKinds:["player","enemy","goal"]},
simulation:{genre:"simulation",camera:"top_down",requiredSystems:["movement","camera","inventory","economy"],visualDefaults:{style:"vector",camera:"top_down",paletteMood:"systemic",characterAnimation:false,tileBased:true},minimumScenes:1,requiredEntityKinds:["player","npc","item"]},
survival:{genre:"survival",camera:"top_down",requiredSystems:["movement","collision","camera","survival","inventory"],visualDefaults:{style:"original_pixel_art",camera:"top_down",paletteMood:"danger",characterAnimation:true,tileBased:true},minimumScenes:1,requiredEntityKinds:["player","enemy","item"]}
};
export function resolve2DGenre(input:string|GameBlueprint):GenreProfile2D|null{const t=(typeof input==="string"?input:[input.title,input.concept,input.genre,input.theme,input.world,input.coreLoop,...input.mechanics].join(" ")).toLowerCase();if(/pokemon|pokémon|monster tamer|monster-tamer|creature tamer|monster trainer|monster collection|creature collection/.test(t))return P.monster_tamer;if(/farming|farm|bertani|tanam|panen|kebun|ternak/.test(t))return P.farming;if(/platformer|platform|lompat|jump and run/.test(t))return P.platformer;if(/racing|race|balap|racer/.test(t))return P.racing;if(/puzzle|teka-teki|teka teki|match-3|logic/.test(t))return P.puzzle;if(/shooter|shooting|menembak|tembak/.test(t))return P.shooter;if(/strategy|strategi|tower defense/.test(t))return P.strategy;if(/simulation|simulasi|management|tycoon/.test(t))return P.simulation;if(/survival|bertahan|zombie|horror|horor/.test(t))return P.survival;if(/rpg|role playing|role-playing/.test(t))return P.rpg;if(/adventure|petualangan|explore|eksplorasi/.test(t))return P.adventure;return null}
export function getGenreProfile(g:Engine2DGenre){return P[g]}
