import type { GameSpecification2D } from "./types";

const esc=(s:string)=>s.replace(/</g,"\\u003c");

export function build2DGameHtml(spec:GameSpecification2D):string{
  const json=JSON.stringify(spec).replace(/</g,"\\u003c");
  const html=[
'<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">',
'<title>'+esc(spec.title)+'</title><style>*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#111827;color:#fff;font-family:system-ui,sans-serif}#root{position:relative;width:100%;height:100dvh;overflow:hidden}canvas{width:100%;height:100%;display:block;image-rendering:pixelated;touch-action:none}#hud{position:absolute;left:10px;right:10px;top:10px;display:flex;justify-content:space-between;gap:8px;pointer-events:none}.card{background:#0b1220dd;border:1px solid #ffffff22;border-radius:12px;padding:8px 10px;font-size:12px}#tutorial{position:absolute;inset:0;display:grid;place-items:center;background:#020617cc;z-index:5}#tutorial .box{width:min(92vw,480px);padding:22px;border-radius:18px;background:#111827;border:1px solid #ffffff20}button{border:0;border-radius:10px;padding:10px 14px;font-weight:700;background:#22c55e;color:#04130a}#pad{position:absolute;left:18px;bottom:18px;width:150px;height:150px;display:grid;grid-template-columns:repeat(3,1fr);grid-template-rows:repeat(3,1fr);gap:5px;z-index:4}.pad{border:1px solid #ffffff22;background:#0f172acc;color:#fff;border-radius:12px;font-weight:800}#action{position:absolute;right:22px;bottom:38px;z-index:4;width:72px;height:72px;border-radius:50%;background:#f59e0b;color:#111827}</style></head>',
'<body><div id="root"><canvas id="game" width="960" height="640"></canvas><div id="hud"><div class="card"><b id="title"></b><br><span id="objective"></span></div><div class="card">Genre: <span id="genre"></span><br>Progress: <span id="progress">0</span>%</div></div>',
'<div id="tutorial"><div class="box"><h2>Petunjuk Bermain</h2><p>Gunakan WASD / Arrow untuk bergerak. ACTION untuk berinteraksi. Dekati target untuk menjalankan objective.</p><button id="start">Mulai</button></div></div>',
'<div id="pad"><button class="pad" data-dir="up">▲</button><button class="pad"></button><button class="pad" data-dir="up">▲</button><button class="pad" data-dir="left">◀</button><button class="pad" data-dir="down">▼</button><button class="pad" data-dir="right">▶</button><button class="pad"></button><button class="pad" data-dir="down">▼</button><button class="pad"></button></div><button id="action">ACTION</button></div>',
'<script>(function(){',
'var SPEC='+json+';var c=document.getElementById("game"),x=c.getContext("2d"),keys=new Set(),touch=new Set(),started=false,won=false,lost=false,progress=0,frames=0,anim=0,last=performance.now();',
'var sceneIndex=0;var p={x:160,y:180,speed:180};var state={scene:SPEC.scenes[0].id,playerX:p.x,playerY:p.y,progress:0,won:false,lost:false,actionCount:0};var tutorial={available:true,shown:true};',
'function resize(){var d=Math.min(2,devicePixelRatio||1),r=c.getBoundingClientRect();c.width=Math.max(320,Math.floor(r.width*d));c.height=Math.max(240,Math.floor(r.height*d));x.setTransform(c.width/960,0,0,c.height/640,0,0)}addEventListener("resize",resize);resize();',
'function direction(){return{x:(keys.has("d")||keys.has("arrowright")||touch.has("right")?1:0)-(keys.has("a")||keys.has("arrowleft")||touch.has("left")?1:0),y:(keys.has("s")||keys.has("arrowdown")||touch.has("down")?1:0)-(keys.has("w")||keys.has("arrowup")||touch.has("up")?1:0)}}',
'function move(dt){var d=direction(),m=Math.hypot(d.x,d.y)||1;p.x=Math.max(30,Math.min(930,p.x+d.x/m*p.speed*dt));p.y=Math.max(90,Math.min(600,p.y+d.y/m*p.speed*dt));}',
'function action(){state.actionCount++;var es=SPEC.scenes[sceneIndex].entities;for(var i=0;i<es.length;i++){var e=es[i];if((e.kind==="creature"||e.kind==="item"||e.kind==="npc")&&Math.hypot(p.x-e.x,p.y-e.y)<90){progress=Math.min(100,progress+(e.kind==="creature"?50:25));state.progress=progress}}if(sceneIndex<SPEC.scenes.length-1&&progress>=50){sceneIndex++;state.scene=SPEC.scenes[sceneIndex].id;p.x=100;p.y=180}if(progress>=100){won=true;state.won=true}}',
'function draw(){var scene=SPEC.scenes[sceneIndex];var bg=scene.id==="village"?"#31572c":scene.id==="route"?"#806b3f":scene.id==="forest"?"#193d2b":SPEC.visual.paletteMood==="cozy pastoral"?"#5b7f3b":"#172554";x.fillStyle=bg;x.fillRect(0,0,960,640);x.globalAlpha=.16;for(var gx=0;gx<960;gx+=48)for(var gy=70;gy<640;gy+=48){x.fillStyle=(gx/48+gy/48)%2?"#fff":"#000";x.fillRect(gx,gy,48,48)}x.globalAlpha=1;var es=scene.entities;for(var i=0;i<es.length;i++){var e=es[i];if(e.kind==="player")continue;var col=e.kind==="npc"?"#38bdf8":e.kind==="creature"?"#c084fc":e.kind==="item"?"#facc15":e.kind==="goal"?"#22c55e":"#64748b";x.fillStyle=col;x.fillRect(e.x-16,e.y-16,32,32);x.fillStyle="#fff";x.font="11px system-ui";x.fillText(e.label,e.x-28,e.y-23)}x.fillStyle=["#f5cfa0","#60a5fa","#f59e0b","#22c55e"][anim%4];x.fillRect(p.x-14,p.y-18,28,36);x.fillStyle="#111827";x.fillRect(p.x-9,p.y-8,5,5);x.fillRect(p.x+4,p.y-8,5,5)}',
'function tick(now){var dt=Math.min(.05,(now-last)/1000);last=now;if(started&&!won&&!lost){move(dt);anim=Math.floor(now/160)%4;frames++;state.playerX=p.x;state.playerY=p.y}draw();document.getElementById("progress").textContent=String(progress);requestAnimationFrame(tick)}',
'document.getElementById("start").onclick=function(){started=true;tutorial.shown=false;document.getElementById("tutorial").style.display="none"};addEventListener("keydown",function(e){keys.add(e.key.toLowerCase());if(e.key===" "){action();e.preventDefault()}});addEventListener("keyup",function(e){keys.delete(e.key.toLowerCase())});',
'document.querySelectorAll("[data-dir]").forEach(function(b){var d=b.dataset.dir;b.onpointerdown=function(){touch.add(d)};b.onpointerup=b.onpointercancel=function(){touch.delete(d)}});document.getElementById("action").onpointerdown=action;',
'document.getElementById("title").textContent=SPEC.title;document.getElementById("objective").textContent=SPEC.objective;document.getElementById("genre").textContent=SPEC.genre;requestAnimationFrame(tick);',
'window.__RK_2D_ENGINE_V2__={version:"2.0.0",genre:SPEC.genre,systems:SPEC.systems,sceneCount:SPEC.scenes.length};window.__RK_GAME_TEST__={',
'getState:function(){return Object.assign({},state,{started:started,sceneIndex:sceneIndex})},getPlayerState:function(){return{x:p.x,y:p.y}},getObjectiveState:function(){return{progress:progress,objective:SPEC.objective}},getWinState:function(){return{won:won}},getLoseState:function(){return{lost:lost}},getTutorialState:function(){return Object.assign({},tutorial)},getControlState:function(){return{up:true,down:true,left:true,right:true}},',
'performTestAction:function(a){if(a==="action")action()},testDirectionalControl:function(d){touch.add(d);setTimeout(function(){touch.delete(d)},80);return true},restart:function(){sceneIndex=0;progress=0;won=false;lost=false;p.x=160;p.y=180;state.scene=SPEC.scenes[0].id;state.progress=0;state.won=false;state.lost=false;state.actionCount=0;started=true}};',
'})();</script></body></html>'
];
return html.join("");
}
