import type { GameSpecification2D, GenreRuntimePlan } from "../types";
import { build2DRuntimeHtml } from "../sharedRuntime";

export function buildMonsterTamerRuntime(spec:GameSpecification2D):string{
  const s=[
"var state={x:160,y:430,hp:100,coins:50,scene:'village',dialogueStarted:false,questAccepted:false,encounterStarted:false,battleStarted:false,enemyHp:45,captureCount:0,partyCount:0,turns:0,won:false,lost:false};",
"function resetState(){state={x:160,y:430,hp:100,coins:50,scene:'village',dialogueStarted:false,questAccepted:false,encounterStarted:false,battleStarted:false,enemyHp:45,captureCount:0,partyCount:0,turns:0,won:false,lost:false}}",
"function restartGame(){resetState();won=false;lost=false;hideMessage()}",
"function onStart(){resetState()}",
"function getGenreStats(){return state.scene.toUpperCase()+' · '+(state.questAccepted?'QUEST ON':'TALK TO MENTOR')+' · PARTY '+state.partyCount+' · CAPTURE '+state.captureCount+' · HP '+state.hp}",
"function getObjectiveState(){var p=state.partyCount?1:state.captureCount?.8:state.battleStarted?.58:state.encounterStarted?.44:state.questAccepted?.25:state.dialogueStarted?.12:0;return{progress:p,status:state.won?'won':state.lost?'lost':'playing',scene:state.scene}}",
"function getGenreState(){return{dialogueStarted:state.dialogueStarted,questAccepted:state.questAccepted,encounterStarted:state.encounterStarted,battleStarted:state.battleStarted,battleCompleted:state.encounterStarted&&!state.battleStarted,captureCount:state.captureCount,partyCount:state.partyCount}}",
"function testDirection(d){var bx=state.x,by=state.y;input[d]=true;commonMove(150,.12);input[d]=false;return d==='left'?state.x<bx:d==='right'?state.x>bx:d==='up'?state.y<by:state.y>by}",
"function performGameAction(a){started=true;state.turns++;if(a==='move'||a==='explore'){testDirection('right');return true}if(a==='talk'){state.dialogueStarted=true;return true}if(a==='accept_quest'){if(state.dialogueStarted){state.questAccepted=true;return true}return false}if(a==='encounter'){if(state.questAccepted){state.encounterStarted=true;state.battleStarted=true;state.scene='route';return true}return false}if(a==='attack'){if(state.battleStarted){state.enemyHp=testMode?0:Math.max(0,state.enemyHp-18);if(state.enemyHp===0){state.battleStarted=false}return true}return false}if(a==='capture'){if(state.encounterStarted&&!state.battleStarted){state.captureCount=1;state.coins=Math.max(0,state.coins-10);return true}return false}if(a==='add_party'){if(state.captureCount){state.partyCount=1;state.scene='forest';finish(true,'PARTY TERBENTUK','Creature pertama masuk party.');return true}return false}if(a==='action'){if(!state.dialogueStarted)return performGameAction('talk');if(!state.questAccepted)return performGameAction('accept_quest');if(!state.encounterStarted)return performGameAction('encounter');if(state.battleStarted){performGameAction('attack');performGameAction('attack');performGameAction('attack');return true}if(!state.captureCount)return performGameAction('capture');return performGameAction('add_party')}return false}",
"function updateGame(dt){commonMove(150,dt)}",
"function renderGame(){ctx.clearRect(0,0,W,H);ctx.fillStyle=state.scene==='village'?'#6f9d63':state.scene==='forest'?'#2d5936':'#88945a';ctx.fillRect(0,0,W,H);for(var gx=0;gx<W;gx+=42)for(var gy=90;gy<H;gy+=42){ctx.fillStyle=(gx/42+gy/42)%2?'#ffffff09':'#00000009';ctx.fillRect(gx,gy,42,42)}if(state.scene==='village'){ctx.fillStyle='#b66e48';ctx.fillRect(55,155,210,130);ctx.fillStyle='#d9b06e';ctx.beginPath();ctx.moveTo(35,155);ctx.lineTo(160,75);ctx.lineTo(285,155);ctx.fill();ctx.fillStyle='#3b6f87';ctx.fillRect(420,205,62,80);text('MENTOR',418,194,12)}else if(state.scene==='route'){for(var i=0;i<8;i++){circle(70+i*92,170+(i%3)*72,22,'#2e6339')}if(state.encounterStarted)circle(W-150,300,34,'#d9844c')}else{for(var j=0;j<12;j++)circle(60+(j*73)%W,135+(j*51)%(H-180),20,'#245033');ctx.fillStyle='#d0b36d';ctx.fillRect(W-170,H-160,120,70);text('FOREST ALTAR',W-165,H-170,11)}if(state.battleStarted){ctx.fillStyle='#14111d';ctx.fillRect(80,170,W-160,250);text('BATTLE',100,205,20);circle(W-195,275,48,'#d9854e');circle(200,350,48,'#6aa8dc');text('WILD HP '+state.enemyHp,W-280,350,13);text('ATTACK untuk melemahkan',100,460,12)}circle(state.x,state.y,17,'#67a8e6');ctx.fillStyle='#f0d0b1';ctx.fillRect(state.x-8,state.y-25,16,8)}"
].join("\n");
  const plan:GenreRuntimePlan={genre:"monster_tamer",runtimeId:"monster-tamer-v1",label:"Monster Tamer World",palette:{background:"#14251b",panel:"#182b20",ground:"#376a3b",accent:"#e6c56a",danger:"#b84d58",light:"#f4f0d8"},tutorial:{title:"Monster Tamer 2D",body:"Jelajahi desa, bicara dengan mentor, terima misi, hadapi creature liar, battle, tangkap creature, lalu masukkan partner ke party."},testActions:["move","talk","accept_quest","encounter","attack","capture","add_party"],sourceVersion:"genre-runtime-v1",script:s};
  return build2DRuntimeHtml(spec,plan)
}
