-- James memory foundation for Tanya Saya
-- Run this migration in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.ai_conversations (
  id uuid primary key,
  user_id text not null,
  title text,
  summary text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.ai_conversations(id) on delete cascade,
  user_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  intent text,
  tool text,
  created_at timestamptz not null default now()
);

create index if not exists ai_conversations_user_id_idx
  on public.ai_conversations(user_id);

create index if not exists ai_messages_user_created_idx
  on public.ai_messages(user_id, created_at desc);

create index if not exists ai_messages_conversation_created_idx
  on public.ai_messages(conversation_id, created_at asc);

alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;

revoke all on table public.ai_conversations from anon, authenticated;
revoke all on table public.ai_messages from anon, authenticated;

grant all on table public.ai_conversations to service_role;
grant all on table public.ai_messages to service_role;

-- James accesses these tables only from the trusted Next.js server
-- using SUPABASE_SECRET_KEY. No browser-side database access is allowed.
